language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_DenisOstapovich_AllLabs
  - make -j
  - ./381706-1_DenisOstapovich_AllLabs
notifications:
  email: false
branches:
  only:
    - Stack
