language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_DenisOstapovich_AllLabs
  - make -j
  - ./StackTest/stack_test
notifications:
  email: false
branches:
  except:
    - master
